[versions]
ksp = "2.2.0-2.0.2"
kotlin = "2.2.0"
kotlinpoet = "2.2.0"
gradleMavenPublish = "0.34.0"
androidGradlePlugin = "8.10.0"

# region publishing
groupId = "es.horm.kmap"
kmapKspVersion = "0.1.0"
kmapRuntimeVersion = "0.1.0"
# endregion

[libraries]
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp"}
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet"}
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet"}

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin"}

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

gradleMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradleMavenPublish"}
